- server/src/modes/typescriptMode.ts
Don't import `import Vue from 'vue'` if user already imports Vue themselves (perhaps even from somewhere else)
Fixes #128
> Dont duplicate `import Vue`

- package.json
After consulting with @mjbvz, I think this is the fix for the `vue-template-compiler` bugs linked from #136. Unfortunately, I'm not sure how to make a clean install to test the change.
> Add vue-template-compiler to extension manifest

- server/src/modes/javascriptMode.ts
/cc @sandersn 
For #131 and alike, this seems to happen when a project is large.
In one of my project I was able to repro it, and while debugging I found:
https://github.com/octref/vetur/blob/master/server/src/modes/javascriptMode.ts#L50-L67
```ts
const { createLanguageServiceSourceFile, updateLanguageServiceSourceFile } = createUpdater();
(ts as any).createLanguageServiceSourceFile = createLanguageServiceSourceFile;
(ts as any).updateLanguageServiceSourceFile = updateLanguageServiceSourceFile;
const configFilename = ts.findConfigFile(workspacePath, ts.sys.fileExists, 'tsconfig.json') ||
ts.findConfigFile(workspacePath, ts.sys.fileExists, 'jsconfig.json');
const configJson = configFilename && ts.readConfigFile(configFilename, ts.sys.readFile).config || {};
const parsedConfig = …
```
> Exclude node_modules in module resolution

- README.md
This is just a fix.
The link was pointing to "https://github.com/octref/vetur/blob/master/CONTRIBUTING.md" instead of "https://github.com/octref/vetur/blob/master/.github/CONTRIBUTING.md".
> Fixed link to contributing guidelines' file

- client/package.json
- client/yarn.lock
- package.json
- server/package.json
- server/src/modes/script/javascript.ts
- server/yarn.lock
This is done by hooking `precommit` and `vscode:prepublish`.
Maintainers still need to update vue-language-server by `npm version $DIFF` ~~and `npm publish`~~
now prerelease will try to publish new version of vue-language-server.
> Enable automatic yarn lock and vue-language-server version update

- package.json
The thing is `vsce publish` could fail (or sometimes I'd abort it if I realize I forgot something when publishing). In that case I don't want to run `sync` again, especially for `npm publish`.
I'm ok with running two commands each time
```bash
yarn sync
vsce publish
```
> Remove pre publish hook

- .github/CONTRIBUTING.md
- .github/ISSUE_TEMPLATE.md
- build/update-docs.sh
- docs/README.md
- docs/book.json
- docs/emmet.md
- docs/roadmap.md
- package.json
- server/README.md
Replace github.com/octref/vetur with github.com/vuejs/vetur
Replace octref.github.io/vetur with vuejs.github.io/vetur
> Update all octref/vetur GitHub URLs to vuejs/vetur

- server/package.json
- server/src/modes/template/tagProviders/index.ts
- server/src/modes/template/tagProviders/onsenTags.ts
- server/yarn.lock
@octref @HerringtonDarkholme (Cc: @masahirotanaka)
Hi, I'm a developer of [Onsen UI](https://github.com/OnsenUI/OnsenUI), a UI library for mobile development (simliar to Mint UI).
I heard that our chief (@masahirotanaka) talked with you (@octref) in VueConf 2017.
This PR adds support for Onsen UI based on [`OnsenUI/vue-onsenui-helper-json`](https://github.com/OnsenUI/vue-onsenui-helper-json) (already published to NPM registry).
I chose the same structure as [`ElementUI/element-helper-json`](https://github.com/ElementUI/element-helper-json) to avoid complexity.
The completion works as follows:
Could you please review this PR?
> Add Onsen UI support

- server/src/modes/script/serviceHost.ts
Importing vue file from node_modules is questionable practice.
At least for TypeScript compiler, parsing and analyzing vue file in node_modules is a deal breaker.
Instead, users can provide `component.vue.d.ts` file in node_modules.
> fix #321: skip reading vue file in node_modules

- server/src/modes/embeddedSupport.ts
- server/src/modes/test/region.test.ts
A leading </template> indicates region ending, partially fix #367
> improve template region detection

- server/package.json
- server/src/service/test.ts
- server/test/fixtures/app.vue
- server/test/fixtures/component/comp.vue
- server/test/fixtures/node_modules/@types/global/index.d.ts
- server/test/fixtures/node_modules/@types/mod/index.d.ts
- server/test/fixtures/tsconfig.json
- server/test/mocha.opts
- server/yarn.lock
This pull request add tests for language service host. Fix #356 .
vls.validate(doc) is very slow. I will look at how to improve it.
> add integration test for vls service

- server/src/modes/embeddedSupport.ts
- server/src/modes/test/region.test.ts
Now illegal code like `<template><|</template>` gets proper completion.
> Improve template regions inference

- server/src/modes/languageModes.ts
- server/src/modes/script/javascript.ts
- server/src/modes/template/index.ts
- server/src/modes/template/tagProviders/index.ts
- server/src/service/index.ts
- server/src/vueServerMain.ts
If we cannot find out workpath, just disable some feature.
Currently, process.cwd() will return either home dir or root dir. This hangs vetur as whole. If we just disable script service, at least some completion service works.
> fix #348, optimize single file CPU usage

- LICENSE
Simply putting the license in the README leaves **all** of the code copyrighted. This PR amends the issue.
> Add copy of the MIT License

- server/src/modes/script/bridge.ts
- server/src/modes/script/serviceHost.ts
- server/test/fixtures/package.json
This is a simple and easy fix. 
We still have chances to improve.
Playground: https://github.com/octref/TypeScript-Vue-Starter
> support Vue 2.5+ typing

- server/src/modes/script/javascript.ts
Before:
After:
We also need to change Vue's definition file. The screen is captured after local edit to definition file.
cc @octref
> feat: better javascript completion order

- server/package.json
- server/yarn.lock
The new version of Stylus Supremacy addresses [these issues](https://github.com/ThisIsManta/stylus-supremacy/releases/tag/v2.5.0) reported in https://github.com/vuejs/vetur/issues/471.
> Upgraded Stylus Supremacy to version 2.5.0. Fix #471

- server/yarn.lock
This addresses [this issue](https://github.com/ThisIsManta/stylus-supremacy/issues/9#issuecomment-338447458).
https://github.com/ThisIsManta/stylus-supremacy/releases/tag/v2.5.1
> Upgraded Stylus Supremacy to version 2.5.1

- server/src/modes/script/serviceHost.ts
`parseConfigFile` accepts `existingOption` which overwrites user config
use compilerOption as default
> fix #512, prefer user config

- server/src/modes/script/findComponents.ts
- server/src/modes/script/preprocess.ts
- server/src/modes/script/test.ts
- server/test/fixtures/app.vue
- server/test/fixtures/component/comp2.vue
- server/test/fixtures/node_modules/@types/vue/index.d.ts
Fix #502 
This pull request also skips wrapping ts script object, so vetur and ts-loader will align.
The component analysis combines both AST traversal and type checking. More specifically, we only do type analysis on the definition object literal, e.g the argument of `Vue.extend`, which is found by AST traversal.
This approach is independent of Vue's type declaration. So both Vue2.4- and 2.5+ are supported.
> Refactor component analysis

- server/src/modes/template/services/htmlFormat.ts
By wrapping code in `<template>`, we can skip reindent in vetur's code.
@octref  what's your opinion?
> fix formatting comment

- server/package.json
- server/yarn.lock
BootstrapVue recently hit a 1.0.0 release. This commit just bumps the pkg.json dep up to mirror the updated helpers repo.
> chore(server): update bootstrap-vue dep for v1.0.2

- server/src/modes/script/javascript.ts
note this fix still needs further polish.
When script doc cache didn't hit, we provide doc start as definition.
Need to find a way for converting range
> fix #549: resolve definition against definition doc

- docs/formatting.md
the URL for the Prettier configuration file doc was pointing to the old Github page. Fixed it so that it points to the updated page on the official Prettier docs.
> fixed broken link to the prettier config file

- server/src/utils/prettier/index.ts
As shown in [this](https://github.com/vuejs/vetur/issues/477) or [this](https://github.com/vuejs/vetur/issues/574) issue report, current errors in code formatting only prints 
```
Prettier format failed
[Error - 14:06:21] [object Object]
```
which has no information. Printing actual message will be more helpful to the users and can reduce turn-taking time IMO.
> Print e.message instead of e for prettier format errors

- package.json
- yarn.lock
tslint -p always check every file in project, however we can just check staged file. This significantly speed up commit. cc @octref 
Note npm test isn't changed, in case some file change leaks.
> change npm lint to lint-staged

- server/src/modes/vue/scaffoldCompletion.ts
This should fix issue #680. The tab character is automatically converted to the current editor's indentation setting (so it's automatically expanded to 4 spaces or whatever the current config is).
> Make snippets use the editor's indentation settings

- package.json
- server/package.json
- server/src/modes/script/findComponents.ts
- server/src/modes/script/javascript.ts
- server/src/modes/template/parser/htmlParser.ts
- server/src/modes/template/services/htmlCompletion.ts
- server/src/modes/template/services/htmlSymbolsProvider.ts
- server/src/modes/template/tagProviders/htmlTags.ts
- server/src/modes/template/tagProviders/index.ts
- server/src/modes/test-util/completion-test-util.ts
- server/yarn.lock
- yarn.lock
In this TS version [Definite assignment assertions](https://blogs.msdn.microsoft.com/typescript/2018/01/31/announcing-typescript-2-7/#stricter-class-property-checks) were added, that's why this PR contains more than just package update.
> Updates typescript to 2.7.1 version

- server/src/utils/prettier/index.ts
- server/src/utils/prettier/prettier.d.ts
I wasn't able to change the prettier arrowParens options through the vscode settings. This should fix it.
> add arrowParens option

- client/vueMain.ts
In preparation for [Visual Studio Live Share](https://aka.ms/vsls) adding support for "guests" to receive remote language services for Vue.js files, this PR simply updates the current `DocumentSelector` to be limited to `file` and `untitled` (unsaved) files. This way, when someone has the Vetur extension installed, and joins a Live Share session (where files use the `vsls:` scheme), their language services will be entirely derived from the remote/host side, which provides a more accurate and project-wide experience (guests in Live Share don't have local file access to the project they're collaborating with).
If someone joins a Vue.js project using Live Share, and doesn't have the Vetur extension installed, they will automatically receive language services from the host (which is awesome! …
> [Discussion] [Live Share] Restrict language client to file schemes

- docs/.vuepress/config.js
- docs/CHANGELOG.md
This pull request allows documentation to build using vuepress instead of gitbooks, which allows using the advantages of vuepress. 
This configuration file allows the static build to link to the github pages for contribution, as well as configuring the sidebar.
> Add vuepress support for documentation

- server/package.json
- server/yarn.lock
This upgrades `stylus-supremacy` dependency to version 2.12.0.
See also https://github.com/ThisIsManta/stylus-supremacy/releases
> Upgrades Stylus Supremacy to version 2.12.0

- server/package.json
- server/yarn.lock
Upgrading Stylus Supremacy to v2.12.6 fixes https://github.com/vuejs/vetur/issues/918 by https://github.com/ThisIsManta/stylus-supremacy/commit/7f84e522e8d419ef63003bc9907408e72e1845ca
> Upgraded Stylus Supremacy to version 2.12.6

- server/package.json
- server/yarn.lock
@octref This PR will upgrade prettyhtml to 0.2.0. It contains fixes for the ignore directive ``
> upgrade prettyhtml

- docs/formatting.md
- package.json
- server/src/modes/template/services/htmlFormat.ts
js-beautify-html has had many fixes and is a bit more active. They've fixed the force-expand-multiline formatting, which was the biggest issue, in my opinion, that made it very broken. I updated the docs to reflect this. I think it is fair to let people know it is a viable option, considering it's popularity and size.
I also set the default settings to match the [Vue style guide](https://vuejs.org/v2/style-guide/).
I changed `auto` to `force-expand-multiline` because `auto` never seemed to trigger multiline expansion and the style guide states anything more than one attribute should be expanded. Of course, this can be overridden by the config.
> Update js-beautify-html default settings to match Vue style guide

- docs/formatting.md
When viewing the docs at https://vuejs.github.io/vetur/formatting.htm the link to `.prettierrc` configuration was not hyperlinked.
> .prettierrc configuration was not hyperlinked

- .vscodeignore
https://github.com/Microsoft/vscode/issues/62687
Excludes all `.map` files, most `.ts` files, supporting files like `tsconfig.json`, and all tests from the vscode vsix. These files should not be needed in the extension bundle.
Before:
```
vsce package
vetur-0.13.0.vsix (16291 files, 29.33MB)
```
After:
```
vsce-package
vetur-0.13.0.vsix (14499 files, 26.78MB)
```
> Don't include .ts and .map files in vscode extension bundle

- syntaxes/vue-generated.json
- syntaxes/vue-html.YAML
- syntaxes/vue-html.json
- syntaxes/vue.json
- syntaxes/vue.yaml
Fixes #1023. It looks like the current grammar is a hold-over from pre-HTML5 days when double-hypens weren't allowed in comments.
> Allow double-hyphen in HTML comments

- docs/framework.md
- server/src/modes/template/tagProviders/index.ts
With [nuxt v2.4.0](https://github.com/nuxt/nuxt.js/releases/tag/v2.4.0), `nuxt-ts` and `nuxt-ts-edge` arrived.
This pull request adds vetur support for both dependencies.
> Add support for nuxt-ts and nuxt-ts-edge

- server/src/services/vls.ts
Addresses https://github.com/vuejs/vetur/issues/1181. Based on [vscode-eslint's handling](https://github.com/Microsoft/vscode-eslint/blob/ec619b2baa8e7500a451df4156f1973acce315df/server/src/eslintServer.ts#L699) of diagnostics when a document is closed.
> Clear diagnostics on document close

- server/src/modes/script/preprocess.ts
- test/lsp/fixture/client/templateDiagnostics/template-position.vue
- test/lsp/templateDiagnostics/basic.test.ts
Template diagnostics will be placed at invalid positions when the `<template>` block is not on the top of the file. I've fixed how we add `<template>` tag when we pass raw template code to vue-eslint-parser as same as [existing code](https://github.com/vuejs/vetur/blob/master/server/src/modes/template/services/htmlValidation.ts#L24).
> Fix invalid diagnostic range when template block is not placed on the top of file

- server/src/services/typescriptService/transformTemplate.ts
- test/interpolation/diagnostics/basic.test.ts
- test/interpolation/fixture/diagnostics/hyphen-attrs.vue
Currently, when a template includes some attribute having hyphen on its name, the virtual Vue template will be broken and provides numerous errors. This is because the transformer try to generate the attribute name as identifier even though hyphen is invalid character as identifier.
I've simply changed them to string literal to accept hyphen.
> Avoid virtual template code is broken when attribute name has hyphen

- server/src/services/typescriptService/transformTemplate.ts
- test/interpolation/diagnostics/basic.test.ts
- test/interpolation/fixture/diagnostics/v-on.vue
fix #1227 
I'd been casting v-on directive value to `AST.VOnExpression` but it actually can be `ESLintExpression` when the value is 1) simple path `@click="foo.bar"` or 2) function expression `@click="() => foo = 123"`.
ref: https://github.com/mysticatea/vue-eslint-parser/blob/0f241279dc412ff4bb0faa9211233a944465f9b4/src/script/index.ts#L816
In the case 1), there was no issues found because it actually ignores the expression and no diagnostic was provided.
The case 2) causes the issue #1227.
> Handle v-on value correctly when it is single expression

- server/src/services/typescriptService/transformTemplate.ts
- test/interpolation/diagnostics/basic.test.ts
- test/interpolation/fixture/diagnostics/template-literal.vue
fix #1230
I'm not sure the cause but looks like ts printer emits broken template literal when we reuse its AST node for print. Recreating them solves the issue.
> Fix template literal breaks virtual template file

- server/src/services/typescriptService/transformTemplate.ts
- test/interpolation/diagnostics/basic.test.ts
- test/interpolation/fixture/diagnostics/object-literal.vue
Possibly fix... #1237 
This is the same kind of issue with #1244. String and Numeric literal in object literal property key emits invalid characters when reusing AST.
> Fix object literal key breaks virtual template file

- docs/README.md
- docs/framework.md
- server/src/modes/template/tagProviders/index.ts
- test/lsp-ts-28/fixture/package.json
- test/lsp-ts-28/fixture/yarn.lock
- test/lsp/fixture/package.json
- test/lsp/fixture/yarn.lock
TLDR; **I added support for the `vetur` Object in package.json (which specifies the location of Vetur's needed tags and attributes jsons) specifically for Quasar. A later change in Vetur code made this feature available for all frameworks, but removed Quasar support as a result, which is ironic.** Quasar developers are missing the autocompletion feature since 5 November.
This PR re-adds support for Quasar Framework (< v1) when using Quasar CLI.
I initially introduced the concept of using package.json > vetur Object to specify the location of vetur tags and attributes file with [PR](https://github.com/vuejs/vetur/commit/038fe3774cafbdaeda6b6877e1bff21deeb8619d#diff-edc9333e4c2f452171b45de5fcbe9376R28). This was done for Quasar Framework only.
Later on, this concept became the default way …
> fix: Re-add Quasar Framework pre v1 support

- azure-pipelines.yml
- server/src/embeddedSupport/languageModelCache.ts
- server/src/embeddedSupport/languageModes.ts
- server/src/modes/script/javascript.ts
- server/src/modes/style/index.ts
- server/src/modes/style/stylus/index.ts
- server/src/modes/template/htmlMode.ts
- server/src/modes/template/interpolationMode.ts
- server/src/services/typescriptService/preprocess.ts
- server/src/services/typescriptService/serviceHost.ts
- server/src/services/typescriptService/util.ts
- server/src/services/vls.ts
- server/src/utils/paths.ts
- test/interpolation/completion/basic.test.ts
- test/interpolation/completion/helper.ts
- test/lsp-ts-28/definition/basic.test.ts
- test/lsp-ts-28/documentLink/basic.test.ts
- test/lsp-ts-28/references/basic.test.ts
- test/lsp/definition/basic.test.ts
- test/lsp/documentLink/basic.test.ts
- test/lsp/references/basic.test.ts
- Supersedes #1278
- Partially fix a few tests on Windows for #1266
- Fix #1277
> Service host file management improvement

- server/src/services/typescriptService/test/transformTemplate.test.ts
- server/src/services/typescriptService/transformTemplate.ts
By this PR, interpolation service supports following usage:
```vue
<template>
<button @click="() => { foo + 1 }">Increment</button>
</template>
```
I only transform `StatementExpression` in arrow function block because no one would use other statements in template...
> Support statement expression in arrow function block

- server/src/services/typescriptService/bridge.ts
- server/src/services/typescriptService/preprocess.ts
- server/src/services/typescriptService/transformTemplate.ts
- test/interpolation/diagnostics/basic.test.ts
- test/interpolation/fixture/diagnostics/v-on.vue
fix #1281 
Utilizing `HTMLElementEventMap` which has all possible event name and event type pairs for `$event` type.
Note that `ComponentData` bridge type is only meant to be used for inferring `$event` type currently. So it will skip type check in case of passing method name directly and `v-on` without argument like below:
```vue
<template>
<div>
<input @keydown="onClick($event)" />
<input @keydown="onClick" />
<input v-on="{ keydown: onClick }" />
</div>
</template>
<script lang="ts">
import Vue from 'vue'
export default Vue.extend({
methods: {
onClick(event: MouseEvent): void {}
}
})
</script>
```
This is because there are no guarantee that the event is from native DOM elements. e.g. when some Vue component emits string value via `change` event which is the same name with native DOM …
> Infer $event type more accurately

- server/src/services/typescriptService/preprocess.ts
- server/src/services/typescriptService/transformTemplate.ts
`createStatement` is deprecated, use `createExpressionStatement` instead.
> substitute `createStatement` with `createExpressionStatement`

- docs/framework.md
- server/package.json
- server/src/modes/template/tagProviders/externalTagProviders.ts
- server/src/modes/template/tagProviders/index.ts
- server/yarn.lock
- test/lsp/completion/template.test.ts
- test/lsp/fixture/client/completion/template/Vuetify.vue
- test/lsp/fixture/package.json
- test/lsp/fixture/yarn.lock
switched to using `vetur` option inside package.json for auto-completion instead of separate package.
also added support through @nuxtjs/vuetify package
> feat: remove vuetify-helper-json and use runtime pkg info

- server/src/services/typescriptService/transformTemplate.ts
- test/interpolation/diagnostics/basic.test.ts
- test/interpolation/fixture/diagnostics/v-on.vue
Sometimes the users want to write `v-on` with empty value like `@click.stop`. In this case, Vetur produce an error because it passes `true` as the value on virtual source file.
Changing the value to noop solves this issue.
> Avoid template diagnostic error on empty v-on

- server/src/services/typescriptService/bridge.ts
fix #1306 
I said `$event` is only used native event handler but it was not true actually.
We can use it in component event handler and it refers the first parameter of event.
https://vuejs.org/v2/guide/components.html#Emitting-a-Value-With-an-Event
I guess we should relax its type to `any` until we can detect component tag in future.
> Relax $event type to any

- server/src/services/typescriptService/sourceMap.ts
- server/src/services/typescriptService/test/sourceMap.test.ts
- server/src/services/typescriptService/test/transformTemplate.test.ts
- server/src/services/typescriptService/transformTemplate.ts
- server/src/services/typescriptService/walkExpression.ts
- test/interpolation/diagnostics/basic.test.ts
- test/interpolation/fixture/diagnostics/trivia.vue
Trying to resolve the issue that the source map location is differed when there are extra space / less space like:
```vue
<template>
<div v-if="
!loading1
&& !loading2
">
Hi
</div>
</template>
```
In the above case the expression in `v-if` will be transformed to `!loading && !loading2` (space and line breaks are removed). Then the diagnostics will point wrong location.
To resolve it, I changed the AST transformer to set source map range for every expression node and merge it when generating source map.
With this approach, the diagnostics point correct location but the source map test is failing because it doesn't correct locations other than expression node like `&&` on the above example. I'll investigate how to deal with this problem.
> Improve source map position accuracy

- CHANGELOG.md
- server/src/services/typescriptService/test/sourceMap.test.ts
- server/src/services/typescriptService/test/transformTemplate.test.ts
- server/src/services/typescriptService/transformTemplate.ts
This PR fixes the problem I stated in #1446.
The reason an invalid expression has gone from source map node is because ESLint does not provide any AST when it is invalid. In the previous implementation, we use range data from ESLintExpression, then we couldn't take an invalid expression when setting source map range.
This PR makes it uses VExpressionContainer which always provides range data whether the contained expression is invalid or not.
> Analyze invalid interpolation expression

- docs/FAQ.md
I have been seeing many people do not know about `Vetur: Use Workspace Dependencies` setting and ask question on this repo's issue list or other forum. Adding a section about it in FAQ may be helpful.
> Add FAQ section to describe workspace dep setting

- CHANGELOG.md
- package.json
- syntaxes/markdown-vue.json
- test/grammar/fixture/embedded.md
- test/grammar/results/embedded_md.json
Hello,
This PR adds vue language injection to markdown fenced code blocks with `vue` identifier, it allows syntax highlighting for SFCs inside Markdown.
I'm not a VSCode extension developer so I followed the stuff [mentioned here](https://code.visualstudio.com/api/language-extensions/syntax-highlight-guide#injection-grammars) and in #1024
I'm not sure how I would add this to the tests though, any pointers would be great!
closes #1024
> feat: added fenced code support for markdown files

- syntaxes/vue-generated.json
- syntaxes/vue-html.YAML
- syntaxes/vue-html.tmLanguage.json
- syntaxes/vue.tmLanguage.json
- syntaxes/vue.yaml
- test/grammar/fixture/TemplateTag.vue
- test/grammar/results/Html_vue.json
- test/grammar/results/Issue1465_vue.json
- test/grammar/results/TemplateTag_vue.json
End the vue-html only with a `</template>` at the beginning of a line.
Because the `<template>` tag starts a grammar in source.vue files and
can also be used a a tag *within* that grammar, the closing
`</template>` of the grammar must be distinguishable from the same
closing tag within the vue-html grammar.
This enables removing the recursive application of the vue-html grammar
within the vue-html grammar because source.vue can reliably know when
a `</template>` should end the grammar.
* New restriction: there can be only 1 closing `</template>` within a
Vue single-file component (SFC) otherwise the vue-html grammar will
be closed early. That closing `</template>` must also appear at the
beginning of a line. Because this follows Vue formatting guidelines,
this should have zero impact on …
> Prevent linebreak in </template> from breaking syntax highlighting

- server/src/modes/template/tagProviders/index.ts
I suggest allowing quasar to be a devDependency to allow code completion in app extensions without adding a dependency.
https://github.com/quasarframework/quasar-starter-kit-app-extension/issues/10
> quasar as devDependency

- docs/framework.md
Seems like the URL has changed, as it can be seen in their GitHub repository.
[The new URL](https://quasar.dev/)
> Update the Quasar Framework's URL in framework.md

- server/src/services/vls.ts
- server/src/utils/paths.ts
vscode-uri use lower-case drive-letter. So convert it always in getFilePath()
Fixes https://github.com/vuejs/vetur/issues/1316
> Fix Windows paths.

- server/src/services/typescriptService/bridge.ts
- test/interpolation/fixture/hover/Basic.vue
- test/interpolation/hover/basic.test.ts
When array is readonly, I will get `any` in `v-for` element.
> Fix template interpolation in vfor when readonly array

- docs/framework.md
> docs: fix a misspelled word

- server/src/services/typescriptService/sourceMap.ts
i found a big performance issue when open a big vue project, and fix it , pass all test.
> improvement: improve performance

- server/src/modes/template/tagProviders/index.ts
- server/src/modes/template/tagProviders/nuxtTags.ts
Hi :) 
This PR adds integration with [nuxt/components](https://github.com/nuxt/components) (nuxt/components#14). I also did some refactors for `nuxtTags.ts` and also checking `devDependencies`. `nuxt-legacy` is no longer valid and `nuxt-ts` is installed alongside with nuxt dependency.
Locally working. The only issue is that I don't know if we can somehow reload vetur tags or not?
> feat: detect tags from @nuxt/components

- vti/src/cli.ts
- vti/src/initParams.ts
[VS Code Language Server sends `SIG_0` to parent process](https://github.com/microsoft/vscode-languageserver-node/blob/master/server/src/main.ts#L1899-L1911), to make sure it's still alive. However, calling `kill` with `SIG_0` also performs permission check, and since VTI passes 1 as processId - `kill` fails and language server thinks the parent process doesn't exist.
This PR suggests a fix to this problem by passing a real PID.
Resolves: #1699
> Pass correct PID to language server

- server/src/services/vls.ts
This solves #977 and builds upon the work of #1634 
Without this fixes I wasn't able to initialize the server for Emacs Eglot without errors, it should solve the same issues on other clients.
Notice I'm using the "optional chaining operator" on the `VLSFullConfig` assignation (given that this project uses Babel).
> Fixes errors when no initialization options are given to vue-language-server

- client/vueMain.ts
- test/interpolation/completion/basic.test.ts
- test/interpolation/diagnostics/basic.test.ts
- test/interpolation/diagnostics/helper.ts
- test/interpolation/helper.ts
- test/interpolation/hover/basic.test.ts
- test/lsp/features/codeAction/basic.test.ts
- test/lsp/features/completion/pathCompletion.test.ts
- test/lsp/features/completion/scaffold.test.ts
- test/lsp/features/completion/script.test.ts
- test/lsp/features/completion/style.test.ts
- test/lsp/features/definition/basic.test.ts
- test/lsp/features/diagnostics/basic.test.ts
- test/lsp/features/diagnostics/eslint.test.ts
- test/lsp/features/diagnostics/helper.ts
- test/lsp/features/diagnostics/unused.test.ts
- test/lsp/features/documentColor/basic.test.ts
- test/lsp/features/documentHighlight/basic.test.ts
- test/lsp/features/documentLink/basic.test.ts
- test/lsp/features/documentSymbol/basic.test.ts
- test/lsp/features/formatting/basic.test.ts
- test/lsp/features/hover/basic.test.ts
- test/lsp/features/references/basic.test.ts
- test/lsp/helper.ts
- test/vue3/features/completion/basic.test.ts
> Speed up and stabilize e2e test

- vti/src/cli.ts
I fix a situation when you write incorrect first args.
Original version no display message.
I change the condition to display message always when not run any other action.
> fix: VTI - Wrong first arg

- test/interpolation/features/beforeAll/beforeAll.test.ts
- test/interpolation/features/completion/basic.test.ts
- test/interpolation/features/completion/helper.ts
- test/interpolation/features/diagnostics/basic.test.ts
- test/interpolation/features/diagnostics/helper.ts
- test/interpolation/features/hover/basic.test.ts
- test/interpolation/fixture/beforeAll.vue
- test/interpolation/helper.ts
- test/interpolation/util.ts
- test/lsp/features/beforeAll/beforeAll.test.ts
- test/lsp/fixture/beforeAll.vue
- test/lsp/helper.ts
- test/vue3/features/beforeAll/beforeAll.test.ts
- test/vue3/features/diagnostics/eslint.test.ts
- test/vue3/features/diagnostics/helper.ts
- test/vue3/fixture/beforeAll.vue
- test/vue3/helper.ts
- test/vue3/util.ts
Windows CI sometimes fails on first test (waiting for codeActions). I think the issue is that LS hasn't started.
This PR fixes that by opening a Vue file before each integration test suite and waiting 3s.
> Prevent failure due to slow LS start

- CHANGELOG.md
- server/src/modes/template/services/htmlCompletion.ts
- server/src/modes/template/services/htmlHover.ts
- server/src/modes/template/tagProviders/common.ts
- server/src/modes/template/tagProviders/externalTagProviders.ts
- test/interpolation/features/completion/basic.test.ts
- test/interpolation/fixture/completion/Parent.vue
- test/interpolation/fixture/completion/TestComp.vue
> Handle same tag name. Fix #2049

- server/src/modes/script/javascript.ts
- test/lsp/features/completion/script.test.ts
- test/lsp/fixture/completion/script/Hyphen.vue
> Fix object property completion when have hyphen

- CHANGELOG.md
- server/src/modes/script/childComponents.ts
- server/src/modes/script/componentInfo.ts
- test/interpolation/fixture/completion/Basic.vue
- test/lsp/features/completion/template.test.ts
- test/lsp/fixture/completion/template/childComponent/Child.vue
- test/lsp/fixture/completion/template/childComponent/Child1775.vue
- test/lsp/fixture/completion/template/childComponent/Parent1775.vue
> Fix no props completion when child component `export default {}` ends with `;`

- server/src/services/typescriptService/serviceHost.ts
- server/src/services/typescriptService/util.ts
- server/src/services/typescriptService/vueSys.ts
- Include ".vue" files in projectFiles (using ScriptKind.Deferred)
- Use project files to determine virtual file interpolation (instead of checking for `node_modules` in path)
Fixes #1127
> Allow analyzing Vue files in `node_modules`

- server/src/modes/script/componentInfo.ts
- test/interpolation/features/completion/property.test.ts
- test/interpolation/fixture/completion/propertyDecorator/Child.vue
For #1323 
I find some problems when doing #2141 
I write some wrong logics when use `PropSync` and `Model` decorators.
ref:
- https://github.com/kaorun343/vue-property-decorator#-propsyncpropname-string-options-propoptions--constructor--constructor---decorator
- https://github.com/kaorun343/vue-property-decorator#-modelevent-string-options-propoptions--constructor--constructor---decorator
> Fix PropSync and Model decorators for vue property decorator

- docs/FAQ.md
- server/src/config.ts
- server/src/services/dependencyService.ts
- server/src/services/vls.ts
Naive attempt (proof of concept) to fetch TS runtime based on the `vscode.typescript.tsdk` setting with a fallback to `node_modules`. This will allow to use yarn@berry patched TS runtime as stated in #1711
I'd like to get some feedback/help to finalize this PR
> fix(#1711) Get workspace typescript with the tsdk path (yarn@berry compat)

- CHANGELOG.md
- server/src/modes/template/services/vuePropValidation.ts
- test/interpolation/features/diagnostics/propsValidation.test.ts
- test/interpolation/fixture/diagnostics/propsValidation/parent.vue
This PR fixes problem with 'PascalCase' component names in vue templates.
> Fix prop validation diagnostics not working for PascalCase components in templates 

- README.md
The original "green" is a bit too saturated and having less contrast with the white text in my opinion. Not sure if you like the change though.
Using the Vue's color #42b883. Now it looks like this:
Another idea might be to use the other color #35495e together, which is not part of this PR. If you like it, I can change to it for sure :)
> chore: use Vue's theme color for badges

- CHANGELOG.md
- server/src/modes/script/javascript.ts
- server/src/modes/template/interpolationMode.ts
In `.ts` file, VSCode shows JSDoc in multiple lines.
So I changed it to make Vetur acts the same.
refs b88a39d e21fe22
This PR includes a user-facing change but it does not affect most users, since this change is based on a unreleased change.
Should I update `CHANGELOG.md`?
> Add line break in JSDoc

- server/src/modes/template/htmlMode.ts
- server/src/modes/template/index.ts
- server/src/modes/template/parser/htmlParser.ts
- server/src/modes/template/services/htmlFolding.ts
- server/src/modes/template/tagProviders/htmlTags.ts
Fixed #2234 
Ref: https://github.com/microsoft/vscode-html-languageservice/blob/master/src/services/htmlFolding.ts
> Add HTML folding

- CHANGELOG.md
- server/src/modes/script/componentInfo.ts
- server/src/modes/template/services/vuePropValidation.ts
- server/src/services/vueInfoService.ts
- test/interpolation/features/diagnostics/propsValidation.test.ts
- test/interpolation/fixture/diagnostics/propsValidation/object-validator-props-child.vue
- test/interpolation/fixture/diagnostics/propsValidation/parent.vue
- test/interpolation/fixture/diagnostics/propsValidation/pass-parent.vue
> Fix corner case and add v-model support when prop validation

- CHANGELOG.md
- server/src/modes/script/javascript.ts
> Fix collapse code missing end mark

- CHANGELOG.md
- vti/src/cli.ts
This was due to eslint-plugin-vue errors being ignored
Fixes https://github.com/vuejs/vetur/issues/2305
> 2305 - Fix VTI printing empty filenames

- .github/ISSUE_TEMPLATE/bug_report.md
- .github/PERF_ISSUE.md
- CHANGELOG.md
- README.md
- client/vueMain.ts
- docs/FAQ.md
- package.json
https://github.com/vuejs/vetur/issues/2192#issuecomment-698995835
It can also reload `node_modules` in addition to restart VSCode.
- Add restart action in bug report checklist
> Add restart vue language service command

- CHANGELOG.md
- server/src/modes/script/javascript.ts
- test/lsp/features/completion/script.test.ts
- test/lsp/fixture/completion/script/kindModifiers.vue
- test/vue3/features/completion/basic.test.ts
> Support optional deprecated when completion

- CHANGELOG.md
- client/grammar.ts
- docs/highlighting.md
- package.json
- syntaxes/vue-generated.json
- syntaxes/vue.tmLanguage.json
- syntaxes/vue.yaml
Add [Slim](http://slim-lang.com/) syntax highlighting via [Slim extension](https://marketplace.visualstudio.com/items?itemName=sianglim.slim)
> Add slim syntax highlighting

- CHANGELOG.md
- server/src/embeddedSupport/languageModes.ts
- server/src/modes/script/javascript.ts
- server/src/modes/style/index.ts
- server/src/modes/template/htmlMode.ts
- server/src/modes/template/index.ts
- server/src/modes/template/interpolationMode.ts
- server/src/services/vls.ts
- server/src/utils/cancellationToken.ts
Fixed #1263 
Fix a part of #2192
> Stop computing outdated diagnostics with CancellationToken

- CHANGELOG.md
- server/src/services/typescriptService/preprocess.ts
- test/interpolation/fixture/diagnostics/propTypeValidation/TSChild.vue
- test/vue3/fixture/diagnostics/propTypeValidation/TSChild.vue
> Fix error when optional camel-cased props are missing

- docs/interpolation.md
Changed this line: Vetur will show a **warming** for `<simple>` and an error for `<complex>`.
To this line: Vetur will show a **warning** for `<simple>` and an error for `<complex>`.
> changed warming to warning

- CHANGELOG.md
- server/src/services/vls.ts
Fixed #2388 
It also conveniently fixes a problem where incorrect settings could be imported.
> Refactor to setupConfigure for #2388

- CHANGELOG.md
- server/src/services/typescriptService/preprocess.ts
Fixed #2192
Fixed #2163
Fixed #1731 
Reason: https://github.com/vuejs/vetur/issues/2192#issuecomment-706665715
> Pass version in new template sourceFile for ts perf

- CHANGELOG.md
- client/client.ts
- server/src/services/vls.ts
Per current version of the spec [1], the "documentSelector" is a list of
DocumentFilter and can not contain a string.
It seems like it was allowed to have a string in the past [2] but it's
no longer the case and it doesn't work even in VSCode.
[1] https://microsoft.github.io/language-server-protocol/specification#documentFilter
[2] https://github.com/microsoft/vscode-languageserver-node/issues/685
Resolves #2388
> Fix invalid client/registerCapability request

- CHANGELOG.md
- server/src/services/vls.ts
- test/interpolation/path.ts
On Sublime Text (and potentially other clients) the paths passed to
LSP servers on Windows have an upper-case drive letter. So either:
- `C:\folder\foo`
or
- `file:///C:/folder/foo`
This is problematic with Vetur as it normalizes URI paths received from
the client in notifications and requests like "textDocument/completion",
"textDocument/didChange" etc. It uses `getFileFsPath()` utility path to
get a filesystem path from the URI.
But it doesn't do normalization for the filesystem path received through
`InitializeParams.rootPath` and then uses that path to initialize the
Typescript server. That list (`parsedConfig.fileNames` in `serviceHost.ts`)
is later used to lookup files passed through other calls and causes
issues due to there being duplicate path differing only with drive letter. …
> Fix issue with "File name X differs from already included" on Windows

- server/src/services/dependencyService.ts
> Fix vls initialize is slow

- docs/component-data.md
Hey there,
Ionic Framework recently released Vetur support for the Vue 3 integration in our v5.5.0 release. We would love it if we could get listed on the "Supported Frameworks" section.
Thanks!
> docs(): add ionic framework vetur support

- rfcs/001-vetur-config-file.md
Vetur configuration file.
[Rendered](https://github.com/vuejs/vetur/blob/vetur-config-file-rfc/rfcs/001-vetur-config-file.md)
> Vetur config file RFC

- rfcs/002-monorepo-support.md
How do we support monorepo, sub folder, multi workspace?
[Rendered](https://github.com/vuejs/vetur/blob/monorepo-rfc/rfcs/002-monorepo-support.md)
> Monorepo Support RFC

- server/src/modes/template/tagProviders/externalTagProviders.ts
- server/src/modes/template/tagProviders/index.ts
- server/src/services/typescriptService/vueVersion.ts
- server/src/services/vls.ts
**What's the problem this PR addresses?**
The tag providers can't be located under Yarn PnP due to hard coding `node_modules`
Fixes https://github.com/vuejs/vetur/issues/2469
**How did you fix it?**
- Use require.resolve to locate tag providers
- Setup the PnP hook from the workspace if it exists
> feat: add Yarn PnP support

- README.md
Switch dead `.md` documentation in README links to `.html`. Don't know the source of the issue why `.md` links are broken, but `.html` links at least work.
> Fix dead .md documentation links in README

- server/src/modes/template/services/htmlCompletion.ts
This PR changes `sortText` and `filterText` of completion to make custom attributes more likely to come at the top.
refs #2309
> sort attribute suggestion without `:` or `@`

- build/rollup-plugins.js
The server building would fail on a directory that has space in the path, for example: `c:/my projects/vetur`. Because the spawn of a child process of `tsc` uses the full path as a command like `c:/my projects/vetur/node_modules/.bin/tsc`.
> (dev) fix building in directory that has space in the path

- .prettierignore
- CHANGELOG.md
- server/src/modes/template/services/htmlCompletion.ts
- server/src/modes/template/services/vuePropValidation.ts
- server/src/modes/template/test/completion.test.ts
- test/interpolation/features/completion/property.test.ts
- test/interpolation/fixture/completion/propertyDecorator/Parent.vue
This PR removes used attributes from suggestions except
- it is `class` , because `:class` and `class` can coexist (same with `style`)
- https://eslint.vuejs.org/rules/no-duplicate-attributes.html
- it is a event listener, because it is able to listen to same event by adding modifiers
> Dont include used attributes in suggestions

- CHANGELOG.md
- server/src/modes/script/componentInfo.ts
- server/src/modes/template/tagProviders/componentInfoTagProvider.ts
- server/src/services/typescriptService/preprocess.ts
- server/src/services/typescriptService/transformTemplate.ts
- server/src/services/vueInfoService.ts
- test/interpolation/features/completion/property.test.ts
- test/interpolation/features/diagnostics/propsValidation.test.ts
- test/interpolation/fixture/completion/propertyDecorator/Child.vue
- test/interpolation/fixture/completion/propertyDecorator/Parent.vue
- test/vue3/features/completion/interpolation.test.ts
- test/vue3/features/completion/interpolationClassComponent.test.ts
- test/vue3/features/completion/interpolationProperty.test.ts
- test/vue3/features/diagnostics/emitTypeValidation.test.ts
- test/vue3/fixture/completion/interpolation/Basic.vue
- test/vue3/fixture/completion/interpolation/Parent.vue
- test/vue3/fixture/completion/interpolation/classComponent/Child.vue
- test/vue3/fixture/completion/interpolation/classComponent/Parent.vue
- test/vue3/fixture/completion/interpolation/propertyDecorator/Child.vue
- test/vue3/fixture/completion/interpolation/propertyDecorator/ChildWithEmitsOption.vue
- test/vue3/fixture/completion/interpolation/propertyDecorator/Parent.vue
- test/vue3/fixture/diagnostics/emitTypeValidation/JSChild.vue
- test/vue3/fixture/diagnostics/emitTypeValidation/ParentRight.vue
- test/vue3/fixture/diagnostics/emitTypeValidation/ParentWrong.vue
- test/vue3/fixture/diagnostics/emitTypeValidation/PropertyChild.vue
- test/vue3/fixture/diagnostics/emitTypeValidation/TSChild.vue
- test/vue3/fixture/package.json
- test/vue3/fixture/yarn.lock
This PR implements custom event auto complete.
Obtains data from
```ts
emits: {
foo: () => true,
}
```
and
```ts
emits: ['foo']
```
.
~~Validations are not implemented.~~
close #2392
> Custom event auto complete

- CHANGELOG.md
- server/package.json
- server/yarn.lock
When using Vetur on Vue SFC using stylus, we experienced a formatting bug caused by `stylus-supremacy` related to stylus that is colons were removed unwantedly for deep accessed properties. See https://github.com/ThisIsManta/stylus-supremacy/issues/79
The [2.15.0 release](https://github.com/ThisIsManta/stylus-supremacy/releases/tag/v2.15.0) includes the fix, so I suggest to upgrade it to make it available for the next Vetur release.
All tests passing ✓
> Upgrade stylus-supremacy from 2.14.5 to 2.15.0

- docs/guide/Readme.md
Improved the language in the README in the guide
> Improve language

- server/src/utils/vueVersion.ts
I installed Vue with `yarn add vue@3` and Yarn added `"vue": "3"` to `package.json` and then I configured Vetur to lint my code. For some reason I was getting `vue/no-multiple-template-root` error in a Vue 3 project, I removed Vue and then reinstalled it, but with a specific version and the error was gone. I changed the regexp inside `inferVueVersion` to handle such cases where only major version is saved in `package.json`.
> Improve Vue version detection

- CHANGELOG.md
- vti/package.json
- vti/src/cli.ts
- vti/src/commands/diagnostics.ts
- vti/tsconfig.json
- vti/yarn.lock
Resolves #2451.
Refactoring VTI with [commander.js](https://github.com/tj/commander.js).
```bash
$ vti --help
Usage: vti [options] [command]
Vetur Terminal Interface
Options:
-V, --version            output the version number
-h, --help               display help for command
Commands:
diagnostics [workspace]  Print all diagnostics
help [command]           display help for command
```
- To follow general CLI design, I replaced `vti version` with `vti --version`. Maybe `vti version` should be remained if we need compatibility.
- We also should refactor `diagnostics.ts` but not in the scope for now.
> Refactor VTI with commander.js

- CHANGELOG.md
- server/src/modes/template/htmlMode.ts
- server/src/modes/template/services/vuePropValidation.ts
- test/vue3/features/diagnostics/propTypeValidation.test.ts
- test/vue3/features/diagnostics/propValidation.test.ts
- test/vue3/fixture/diagnostics/propValidation/ParentRight.vue
- test/vue3/fixture/diagnostics/propValidation/TSChild.vue
Fix #2647.
The default prop name in Vue 3 being `modelValue` instead of `value`, a warning is currently shown when using Vue 3 and adding v-model to a component with prop `modelValue` This PR will change the default prop name based on the current Vue version.
> Fix `v-model` default prop name in Vue 3

- server/src/modes/vue/veturSnippets/script/composition-js.vue
- server/src/modes/vue/veturSnippets/script/composition-ts.vue
This adds the feature request, requested by [@Namchee](https://github.com/Namchee) in issue #2741 
I would like to point out that I didn't add an entry to the changelog since there was no section for the upcoming release as it stated in [Pull Request Guidance](https://github.com/vuejs/vetur/wiki/Pull-Request-Guidance) 
> "In CHANGELOG.md, at the end of the section for the upcoming release, add a new line that describes your changes."
But this is what I would have added:
```
- Added new ts and js snippets for the Composition API. Thanks to contribution from [@Namchee](https://github.com/Namchee). #2741
````
Also, I chose not to use the import statement [@Namchee](https://github.com/Namchee) suggested
```js
import { defineComponent } from '@vue/composition-api';
```
but instead opted for: …
> new composition api script snippets for ts and js

- CHANGELOG.md
- vti/src/cli.ts
- vti/src/commands/diagnostics.ts
Resolves #2723.
`vti diagnostics --log-level ERROR` to ignore warns and print only errors.
```bash
$ vti diagnostics --help
Usage: vti diagnostics [options] [workspace]
Print all diagnostics
Options:
-l, --log-level <logLevel>  Log level to print (choices: "ERROR", "WARN", "INFO", "HINT", default: "WARN")
-h, --help                  display help for command
```
> add --log-level option to vti diagnostics

- package.json
- server/src/config.ts
- server/src/embeddedSupport/languageModes.ts
- server/src/modes/script/javascript.ts
- server/src/modes/script/semanticToken.ts
- server/src/modes/script/semanticTokenLegend.ts
- server/src/services/projectService.ts
- server/src/services/vls.ts
- server/src/types.ts
- test/codeTestRunner.ts
- test/lsp/features/semanticTokens/basic.test.ts
- test/lsp/fixture/semanticTokens/Basic.vue
- test/semanticTokenHelper.ts
- test/vue3/features/semanticTokens/basic.test.ts
- test/vue3/fixture/semanticTokens/Basic.vue
Fixed #1904
Fixed #2687
Fixed #2434
Fixed #2687
Add semantic token feature for script region. Due to typescript's implementation. It's currently not available for js. Also because of that, this is currently not available in interpolation mode. But I still left some merging strategy in the project service for potential future implementation. 
A couple of things like to discuss. 
1. There's some new built-in vscode command in [1.53](https://code.visualstudio.com/updates/v1_53#_semantic-token-commands)
Wondering if I should update the integration test to use it. The advantage is it's more integrated than a language-server request. And  I don't have to copy the semantic token legend to the test script. A disadvantage is we might accidentally ship features not compatible with 1.52.  
2. …
> Semantic tokens for typescript

- server/src/modes/template/index.ts
- test/componentData/features/hover/basic.test.ts
- test/componentData/fixture/.vscode/settings.json
- test/componentData/fixture/attributes.json
- test/componentData/fixture/hover/Element.vue
- test/componentData/fixture/package.json
- test/interpolation/features/hover/basic.test.ts
In cases where template interpolation provided some data for the hover
popup, it overrode the popup contents without letting component data
hover info to show.
Ask both services and merge the results together so that nothing is
lost.
Fixes #2878
> Fix component data not shown in hover when template interpolation is on

- docs/guide/snippet.md
Fixes #2927 
The command `npx vuepress build` (in `build/update-docs.sh`) is not bundling the images since the image link in the `docs/guide/snippet.md` is not relative for both the:
- `docs/images/snippet-main.png` _line 39_
- `docs/images/snippet-partial.png` _line 71_
images.
I've tested that my changes work, see the rendered page [here](https://code.stanmd.tk/vetur/guide/snippet.html#customizable-scaffold-snippets). (I'm using GitHub pages just like the project is)
Are the other images in the `docs/images` folder still being used? That is:
- `docs/images/scope.png`
- `docs/images/debug.png`
If not, I guess they should be deleted. I didn't see them referenced anywhere in the project.
> Update snippet.md so that images are rendered

- docs/guide/setup.md
The existing comment ("// shorthand for only root") confused me: I thought it meant there was only one project root, not that only the root is being specified.
> Update project root shorthand comment

- server/src/modes/template/tagProviders/htmlTags.ts
- server/src/modes/template/test/completion.test.ts
- server/src/modes/test-util/completion-test-util.ts
- test/componentData/features/hover/basic.test.ts
- test/componentData/fixture/attributes.json
- test/componentData/fixture/hover/Element.vue
- test/componentData/fixture/tags.json
The code that matches attributes from all providers on hovering
attributes have found a match in the HTML tags provider (htmlTags.ts)
preventing the component data description from showing up.
Include '@' prefix in the collected HTML component data to not match
attributes without '@'. This makes sure that hovering "@click" attribute
matches the HTML provider and hovering "click" doesn't, for example.
This also improves (IMO) completion labels when adding event handlers
tags. Previously all labels for events from HTML provider completions
would not include the `@` prefix which wasn't obvious that it's an
event handler.
Fixes #2900
> Fix attribute description not showing if its name matches html event

- CHANGELOG.md
- vti/src/cli.ts
- vti/src/commands/diagnostics.ts
Resolves https://github.com/vuejs/vetur/issues/2455
`vti diagnostics --files src/App.vue src/Form.vue` to run VTI only on those two files
```
$ vti diagnostics --help
Usage: vti diagnostics [options] [workspace]
Print all diagnostics
Options:
-l, --log-level <logLevel>  Log level to print (choices: "ERROR", "WARN", "INFO", "HINT", default: "WARN")
-f, --files <files...>      Files to diagnose (default: null)
-h, --help                  display help for command
```
> add paths option to vti diagnostics

- README.md
There was a broken link (link error), which has been corrected.
> fix: broken links "semantic-highlighting" in README

- docs/guide/Readme.md
Links were broken because of `/docs` word. Removed from links.
> Fixed borken links.

- package.json
- test/codeTestRunner.ts
- yarn.lock
vscode-test be marked as [deprecated](https://www.npmjs.com/package/vscode-test) on npmjs.org(yarnpkg.com), so just replace vscode-test with latest @vscode/test-electron for `vetur`'s CI. cc @octref  @yoyo930021
> chore: replace deprecated vscode-test with @vscode/test-electron

- docs/guide/setup.md
In order to use Yarn's Typescript SDK we have to set the settings: `useWorkspaceDependencies` to true and then pass Yarn's Typescript SDK path to `typescript.tsdk`; I added an example with some notes to the Yarn PnP section of the setup guide to make it more obvious how to accomplish this.
> Add editor sdk setup notes to Yarn PnP section

- CHANGELOG.md
- server/src/services/typescriptService/bridge.ts
- test/interpolation/fixture/diagnostics/v-for.vue
The `v-for` directive when iterating over a number provides both the 1-based numeric value, and the 0-based index to the iteration function. Vetur currently shows this as an error when you are using the `experimental.templateInterpolationService` option and attempt to use the index.
Existing behavior:
```
No overload matches this call.
The last overload gave the following error.
Argument of type 'number' is not assignable to parameter of type 'object'.Vetur(2769)
```
This change adds the missing second parameter to the iteration helper for the `num: number` overload, and existing usages with a single parameter should continue to work.
> fix(interpolation/v-for): allow optional index parameter for numeric iteration

- docs/guide/component-data.md
Hey there,
BalmUI recently released Vetur support for the Vue 3 integration in our v9.42.0 release and the Vue 2 integration in our v8.49.0 release.
We would love it if we could get listed on the "Supported Frameworks" section.
Thanks!
> docs: add BalmUI for supported framework

- CHANGELOG.md
- server/src/modes/script/componentInfo.ts
- test/interpolation/features/diagnostics/propsValidation.test.ts
- test/interpolation/fixture/diagnostics/propsValidation/object-validator-props-child.vue
- test/interpolation/fixture/diagnostics/propsValidation/pass-parent.vue
This PR allows componentInfo to inspect the `default` and `required` properties of a prop that is set by a variable, i.e. a canned prop declaration.
Example:
CommonProps.ts
```
export const LabelProp = {
type: String,
required: true,
};
export const IsValidProp = {
type: Boolean,
default: false,
};
```
SampleComponent.vue
```
import Vue from 'vue';
import { LabelProp, IsValidProp } from './CommonProps.ts';
export default Vue.extend({
name: 'SampleComponent',
props: {
label: LabelProp,
valid: IsValidProp
}
});
```
> Add support for checking `default` and `required` state of props set by variables (`Identifier`).

- server/src/services/vls.ts
so far, for anything to work, either `rootPath` or `workspaceFolders` need to be set. `rootUri` is a bit "less deprecated" than `rootPath` (https://microsoft.github.io/language-server-protocol/specifications/specification-current/#initialize), so for increased compatibility with LSP clients, I think we should also support that, especially given it is so little effort. Does this make sense to you?
(Example client where this situation applies: https://github.com/AndCake/micro-plugin-lsp/issues/1)
I can't guarantee the tests will all succeed, as for some reason, the test setup fails on my system (even on master). But I guess CI will fire once I submit this PR
> support `rootUri`

- server/src/embeddedSupport/vueDocumentRegionParser.ts
- server/src/modes/script/previewer.ts
- server/src/modes/template/parser/htmlScanner.ts
- server/src/modes/template/test/highlighting.test.ts
- server/src/modes/template/test/scanner.test.ts
- server/src/modes/test-util/completion-test-util.ts
- server/src/modes/test-util/hover-test-util.ts
- server/src/modes/test/region.test.ts
- server/src/utils/strings.ts
[String.prototype.substr()](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/substr) is deprecated so we replace it with [String.prototype.slice()](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/slice) or [String.prototype.substring()](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/substring) which work similarily but aren't deprecated.
.substr() probably isn't going away anytime soon but the change is trivial so it doesn't hurt to do it.
> refactor: replace deprecated String.prototype.substr()

- docs/guide/setup.md
Simply added some more information on how to navigate to VS Code's ```settings.json``` in the docs.
> Fixes vuejs/vetur#3485
