server/src/modes/script/javascript.ts
=> Mark js hover as markedString

client/package.json, server/package.json
We might need lerna to manage multiple package? @octref What's your opinion?
=> Bump version to use 

server/src/modes/script/javascript.ts
=> filter out __vueEditorBridge

server/src/modes/template/services/htmlCompletion.ts, server/src/modes/template/tagProviders/common.ts, server/src/modes/template/tagProviders/elementTags.ts, server/src/modes/template/tagProviders/htmlTags.ts, server/src/modes/template/tagProviders/routerTags.ts, server/src/modes/template/tagProviders/vueTags.ts, server/src/modes/template/test/completion.test.ts, server/src/modes/template/test/scanner.test.ts, server/src/vueServerMain.ts
Fix #255  
Ping @octref since this is quite common usage.
Next step:
=> fix short hand completion

server/src/modes/embeddedSupport.ts, server/src/modes/template/parser/htmlScanner.ts, server/src/modes/test/region.test.ts, server/test/mocha.opts
During editing, nested template will be properly handled.
Before this fix, editing inside nested template will be categorized as vue file, not html.
=> More robust template region detection

README.md
Setup currently points to a 404. I added docs/ to the link to fix it.
=> Fix Setup Link

server/package.json, server/src/modes/embeddedSupport.ts, server/src/modes/script/javascript.ts, server/src/modes/script/typescript.ts, server/src/modes/style/index.ts, server/src/typing.d.ts, server/yarn.lock
Fix https://github.com/octref/vetur/issues/250
=> remove dependency on vue-template-compiler

server/src/modes/script/javascript.ts, server/src/modes/template/services/htmlValidation.ts
allowJS should be always true.
changing compiler option will make TS throw `bucket` not found
=> Fix throwing error when change script lang

README.md
Some of the urls in README is invalid or redirected. This PR is to fix them.
=> doc: fix some invalid or redirected url

server/src/modes/embeddedSupport.ts, server/src/modes/test/region.test.ts
=> fix #293: only collect lang in tempalte tag

package.json, yarn.lock
- Only lint for pre-commit
- Test before push, so commits can be small and break tests & fix in later commit
=> Update husky and pre-commit/push hook

server/src/modes/vue/scaffoldCompletion.ts
=> Add scaffold snippets for scoped style tag

syntaxes/vue-html.YAML, syntaxes/vue-html.tmLanguage
=> fix #328: better tag keyword recognition

server/src/modes/embeddedSupport.ts, server/src/modes/languageModes.ts, server/src/modes/script/javascript.ts, server/src/modes/script/preprocess.ts, server/src/modes/script/serviceHost.ts
Fix #325 
Note this does not magically support JSX typing.
=> support tsx

server/package.json, server/yarn.lock
=> fix #398, bump emmet helper version

server/package.json, server/yarn.lock
=> fix(lint): upgrade eslint-plugin-vue

server/package.json, server/src/modes/script/preprocess.ts, server/src/modes/script/serviceHost.ts, server/yarn.lock
=> upgrade typescript version

docs/setup.md
=> update autofix of eslint and absolute path setting

server/src/vueServerMain.ts
=> feat: add formatOnType support

server/package.json, server/src/modes/template/tagProviders/bootstrapVueTags.ts, server/src/modes/template/tagProviders/common.ts, server/src/modes/template/tagProviders/index.ts, server/yarn.lock
This an attempt to follow the Element UI team's example PR in order to add intellisense to the bootstrap-vue library. Very new to this, so all feedback welcome.
=> feat: add bootstrap-vue intellisense to language server

client/src/vueMain.ts
=> fix: ensure color subscription after client ready

server/package.json
https://github.com/ThisIsManta/stylus-supremacy/releases/tag/v2.7.0
=> Upgraded Stylus Supremacy to version 2.7.0

server/package.json
=> add repo info to server package

package.json, server/src/modes/embeddedSupport.ts, server/src/modes/script/javascript.ts, server/src/modes/script/serviceHost.ts
Fix #606 
@octref Do we need to add an option to turn auto import off?
=> Implement script auto import

server/package.json, server/src/modes/template/tagProviders/externalTagProviders.ts, server/src/modes/template/tagProviders/index.ts, server/yarn.lock
I hope everything looks okay. Modeled it after the previous PRs.
Closes #380
=> feat: added support for vuetify components

server/package.json, server/yarn.lock
https://github.com/ThisIsManta/stylus-supremacy/releases/tag/v2.7.3
=> Upgraded Stylus Supremacy to version 2.7.3

syntaxes/vue-html.YAML, syntaxes/vue-html.json
=> proper fix quoteless value

server/src/modes/script/javascript.ts
Some editor will be broken lsp-server by this error.
=> fix: cannot read property 'completion' of undefined

server/src/modes/script/javascript.ts
For now I think this is a good workaround.
=>  fix #705, skip template completion trigger in script 

server/src/modes/template/parser/htmlParser.ts, server/src/modes/template/parser/htmlScanner.ts, server/src/modes/template/services/htmlCompletion.ts, server/src/modes/template/services/htmlSymbolsProvider.ts, server/src/modes/template/test/completion.test.ts, server/src/modes/template/test/emmet.test.ts, server/src/modes/template/test/hover.test.ts, server/src/modes/template/test/parser.test.ts, server/src/modes/template/test/scanner.test.ts, server/src/modes/template/test/symbols.test.ts
cc @ktsn  
I only implement interpolation parsing. `v-for` is parsed as normal attribute.
I'm still thinking if v-for /v-bind should be handled in template layer.
=> Parse template interpolation

server/src/modes/script/javascript.ts
=> fix get references

syntaxes/vue-html.YAML, syntaxes/vue-html.json
=> Support self closing template tag

server/src/modes/template/tagProviders/vueTags.ts
Tried to streamline things a bit.
=> Adjust grammar and fix typos for v-cloak directive

syntaxes/vue-generated.json, syntaxes/vue-html.YAML, syntaxes/vue-html.json, syntaxes/vue.json, syntaxes/vue.yaml
Afaik snake_case props are valid, but the syntax highlighting was not working for them. I tweaked the appropriate regexes.
Before:
After:
=> Fix syntax highlighting for snake_case props

docs/debugging.md
Set external link as link in markdown syntax
=> Improving Doc, debugging.md

server/package.json, server/src/modes/template/tagProviders/externalTagProviders.ts, server/src/modes/template/tagProviders/index.ts, server/yarn.lock
I'm Buefy core team developer and we would like to add Buefy components support to Vetur.
I didn't try it but i think it's ok.
Thanks!
=> Added support for buefy components

package.json, server/src/utils/prettier/index.ts, server/yarn.lock, yarn.lock
Closes #846
Fixes #835
Fixes prettier/prettier-vscode#498 (closed because it is an issue with Vetur, not their extension: https://github.com/prettier/prettier-vscode/issues/498#issuecomment-415718143)
I had some trouble with the tests, but it seems to be working for me in actual files.
=> Fix Prettier-ESlint support

server/src/vueServerMain.ts
Applying the fix from https://github.com/vuejs/vetur/issues/862#issuecomment-435629045
All credit goes to @AlexKornitzer
=> Fixes #862

server/package.json, server/yarn.lock, test/fixture/client/formatting/VueHNUserView.Expected.vue
for resolve following issues:
<https://github.com/Prettyhtml/prettyhtml/pull/71>
<https://github.com/Prettyhtml/prettyhtml/pull/73>
<https://github.com/Prettyhtml/prettyhtml/pull/75>
1. use tabWidth config for indent script and style tag
2. fix weex component image tag format error 
3. Use snapshot testing,Rerun on tested output to ensure that the formatter is stable.Fix editorconfig to ignore fixtures
and I also changed the format expected result , here is the discuss with prettyhtml author:<https://github.com/Prettyhtml/prettyhtml/issues/74>
thanks~
=> chore: update the prettyhtml version to 0.8.4

server/package.json
https://github.com/vuejs/eslint-plugin-vue/issues/697
i think vetur should also turn off some of rules, they are going to collide with prettier
=> Update eslint-plugin-vue to v5

server/package.json, server/src/modes/template/services/htmlValidation.ts, server/src/typing.d.ts, server/yarn.lock
It would be better to use `@types` declaration rather than own declaration 🙂
=> refactor: use @types/eslint

syntaxes/vue-generated.json, syntaxes/vue-pug.YAML, syntaxes/vue-pug.tmLanguage.json, syntaxes/vue.tmLanguage.json, syntaxes/vue.yaml, test/codeTestRunner.ts, test/grammar/fixture/Html.vue, test/grammar/fixture/Pug.vue, test/grammar/results/Html_vue.json, test/grammar/results/Pug_vue.json
- will fix #1112 
- through reverting 58f72ee
- test throws errors but they were here since 0.16.2
- also added the issue template to the test files
=> Fixed Pug syntax highlighting error when concatenating strings

client/vueMain.ts, server/src/modes/languageModes.ts, server/src/modes/script/javascript.ts, server/src/modes/script/serviceHost.ts, server/src/services/vls.ts, server/src/types.ts, test/lsp/codeAction/basic.test.ts, test/lsp/fixture/client/codeAction/Basic.vue
I'm still not totally familiar with the VS Code API or this codebase, but I just wanted to get this up here to get some early feedback.
What's left?
Related to #871.
=> TypeScript/JavaScript quick fixes & refactorings

server/src/services/vls.ts
This pull request should fix https://github.com/vuejs/vetur/issues/1188
=> Fix TypeError when params.initializationOptions is undefined

server/src/modes/template/interpolationMode.ts, server/src/services/typescriptService/templateDiagnosticFilter.ts, test/interpolation/diagnostics/basic.test.ts, test/interpolation/fixture/diagnostics/member-modifiers.vue, test/interpolation/fixture/package.json, test/interpolation/fixture/tsconfig.json, test/interpolation/fixture/yarn.lock
=> Filter out diagnostics on protected and private members

server/package.json, server/yarn.lock
- Upgrade `gridsome-helper-json` version
- Contributor fills some of the empty lines
=> chore: Upgrade gridsome-helper-json

server/src/services/typescriptService/transformTemplate.ts, test/interpolation/diagnostics/basic.test.ts, test/interpolation/fixture/diagnostics/v-if-and-v-for.vue, test/interpolation/fixture/diagnostics/v-if-narrowing.vue, test/interpolation/fixture/tsconfig.json
=> Support v-if type narrowing

server/src/embeddedSupport/test/embeddedSupport.test.ts, server/src/embeddedSupport/vueDocumentRegionParser.ts, server/src/services/typescriptService/preprocess.ts, test/interpolation/diagnostics/basic.test.ts, test/interpolation/fixture/diagnostics/external-script.ts, test/interpolation/fixture/diagnostics/external-script.vue
=> Support external script for template interpolation

.vscode/launch.json, server/src/services/typescriptService/transformTemplate.ts, test/interpolation/diagnostics/basic.test.ts, test/interpolation/diagnostics/helper.ts, test/interpolation/fixture/diagnostics/v-slot-scope.vue, test/interpolation/fixture/diagnostics/v-slot.vue
fix #1203 
Should be merged after #1208
=> Support scoped slot diagnostics

server/package.json
=> Update js-beautify to 1.10.0

server/src/services/typescriptService/test/transformTemplate.test.ts, server/src/services/typescriptService/transformTemplate.ts
=> Inject `this` to expressions in new expression

server/src/modes/template/modifierProvider.ts, server/src/modes/template/services/htmlCompletion.ts, test/lsp/completion/template.test.ts, test/lsp/fixture/client/completion/template/Basic.vue, test/lsp/fixture/client/completion/template/Item.vue
=> Add Modifiers completion

server/src/services/typescriptService/preprocess.ts
I just reading the code base to learn how this works, and found some code can be improved, feel free to close if don't accept this kind of PR 😄 .
=> Delete unnecessary type argument

CHANGELOG.md, package.json, server/package.json, server/src/modes/script/javascript.ts, server/src/utils/prettier/index.ts, server/src/utils/prettier/prettier.d.ts, server/yarn.lock
Add 'prettier-tslint' support in a simple way. It is useful for me, or maybe other developers who prefer to format code by tslint rules.
=> feat: add 'prettier-tslint' support;

docs/setup.md
The maintainer has changed to Syler.
=> fix(docs): fix Sass extension link

server/src/modes/template/services/htmlFormat.ts
Hi, I want to make prettyhtml in vetur to support .prettierrc (and prettyhtml cli does support .prettierrc https://github.com/Prettyhtml/prettyhtml/blob/6d253d9971ab8b32b3f23824c2581ccb6e18bff4/packages/prettyhtml/cli/args.js#L33)
But I have no idea about how to change the document https://github.com/vuejs/vetur/blob/master/docs/formatting.md#prettyhtml, and where is the unit test for `htmlFormat.ts`
So can anyone help me to improve this PR?
=> prettyhtml support .prettierrc

server/src/modes/vue/index.ts
=> Fix undefined initializationOptions.globalSnippetDir

CHANGELOG.md, server/src/services/typescriptService/transformTemplate.ts, test/interpolation/fixture/hover/Basic.vue, test/interpolation/hover/basic.test.ts
=> Show hover info for v-for variables

docs/interpolation.md
=> Add an example with PropType in interpolation JSDoc section

server/src/services/typescriptService/serviceHost.ts
=> Fix intellisense and other features when open multiple files

server/src/services/typescriptService/serviceHost.ts, server/src/utils/paths.ts
=> Fix add to scriptFileNameSet path format

docs/framework.md
BootstrapVue 2.1+ now bundles auto-generated Vetur helper json files.
=> docs(framework.md): Update BootstrapVue information

client/client.ts, docs/formatting.md, package.json, server/package.json, server/src/embeddedSupport/embeddedSupport.ts, server/src/embeddedSupport/languageModes.ts, server/src/modes/style/sass/sassLanguageMode.ts, server/yarn.lock, test/lsp/fixture/client/formatting/Sass.Expected.vue, test/lsp/fixture/client/formatting/Sass.vue, test/lsp/fixture/client/formatting/TwoStylus.Expected.vue, test/lsp/fixture/client/formatting/TwoStylus.vue, test/lsp/formatting/basic.test.ts
should pass the tests and be ready to merge.
related to #1433
=> add .sass formatting

docs/framework.md, package-lock.json, server/package.json, server/src/modes/template/tagProviders/externalTagProviders.ts, server/src/modes/template/tagProviders/index.ts, test/lsp/fixture/package.json
also added support through nuxt-buefy package
=> feat: remove buefy-helper-json and use runtime pkg info

docs/framework.md
Related PR #1921 
[Rendered](https://github.com/pi0/vetur/blob/2723185051984730c65a3a9fe88ed4f17bd2b088/docs/framework.md)
=> docs: update nuxt in frameworks

docs/formatting.md
intent for Vue tags has been supported. see https://prettier.io/docs/en/options.html#vue-files-script-and-style-tags-indentation
=> update description about prettier

test/lsp/features/completion/template.test.ts, test/lsp/helper.ts, test/vue3/features/diagnostics/eslint.test.ts, test/vue3/features/diagnostics/helper.ts, test/vue3/helper.ts
=> Remove unused sleep functions in tests.

server/src/modes/style/index.ts, server/src/modes/style/sass/sassLanguageMode.ts, server/src/modes/style/stylus/index.ts, test/interpolation/features/completion/helper.ts, test/lsp/features/completion/helper.ts, test/lsp/features/completion/style.test.ts, test/lsp/fixture/completion/style/SassEmmet.vue, test/vue3/features/completion/helper.ts
=> add emmet to sass

CHANGELOG.md, server/package.json, server/yarn.lock
=> Fix prettier-eslint error when formatting in v0.26.0

server/src/config.ts
=> Remove unused useScaffoldSnippets setting

docs/intellisense.md, docs/vti.md, package.json, server/README.md, server/package.json, vti/README.md
=> Remove npm in package.json and add yarn command in docs

CHANGELOG.md, client/vueMain.ts, server/src/modes/script/javascript.ts, server/src/services/vls.ts, server/src/utils/commands.ts
1. Prepare for #1495
2. https://github.com/vuejs/vetur/pull/1704#issuecomment-668793238
=> Use pure server command

server/src/modes/template/services/htmlCompletion.ts, server/src/modes/template/tagProviders/externalTagProviders.ts, test/componentData/features/completion/basic.test.ts, test/componentData/fixture/attributes.json, test/componentData/fixture/completion/Event.vue, test/componentData/fixture/package.json, test/componentData/fixture/tags.json, test/lsp/features/completion/emmet.test.ts, test/lsp/fixture/completion/template/Emmet.vue
Now emmet works normally after interpolation:
Inline style emmet auto-complete support:
Custom event support:
=> Fix #1678 #2173 #2179

CHANGELOG.md, server/src/modes/template/services/htmlSymbolsProvider.ts, server/src/modes/template/test/symbols.test.ts
=> Add showing #slot attrs in symbols

docs/FAQ.md
Added some docs as per earlier discussions here: https://github.com/vuejs/vetur/issues/1707
=> Add mention about computed properties in the FAQ

CHANGELOG.md, server/src/modes/script/javascript.ts, server/src/services/vls.ts, test/lsp/features/completion/script.test.ts, test/lsp/fixture/completion/script/issue-2300.vue
=> Fix no complete literal string union

CHANGELOG.md, vti/src/cli.ts
Add --version command
Usage:
`vti --version` or `vti -v`
Outputs
`v0.0.13`
=> Add version command

CHANGELOG.md, server/src/modes/script/javascript.ts
=> Respect typescript language settings

docs/component-data.md
=> docs: improve docs of component-data

server/src/modes/script/javascript.ts
=> Fix completion ? when optional property

CHANGELOG.md, server/src/services/typescriptService/test/transformTemplate.test.ts, server/src/services/typescriptService/walkExpression.ts, test/interpolation/features/diagnostics/basic.test.ts, test/interpolation/fixture/diagnostics/optional-in-template.vue
=> Fix optional chaining in template

CHANGELOG.md, server/src/embeddedSupport/languageModes.ts, server/src/modes/script/childComponents.ts, server/src/modes/script/componentInfo.ts, server/src/modes/template/htmlMode.ts, server/src/modes/template/index.ts, server/src/modes/template/services/htmlCompletion.ts, server/src/services/autoImportVueService.ts, server/src/services/typescriptService/serviceHost.ts, server/src/services/vueInfoService.ts, test/completionHelper.ts, test/lsp/features/completion/autoImport.test.ts, test/lsp/fixture/completion/autoImport/defineInOneLine.vue, test/lsp/fixture/completion/autoImport/noDefineComponents.vue, test/lsp/fixture/completion/autoImport/sameComponentName.vue, test/util.ts
=> Auto import component in script when completion in template

CHANGELOG.md, vti/package.json, vti/src/cli.ts, vti/yarn.lock
=> Add code frame in vti diagnostics

server/src/services/typescriptService/serviceHost.ts
Fixed #2524 
Fixed #762
Fixed #1896
=> Fix path alias failed when first char is slash

docs/guide/setup.md, docs/reference/Readme.md, rfcs/001-vetur-config-file.md
=> docs: add comma 

docs/guide/FAQ.md
=> Fixes a typo and makes a phrasing suggestion in FAQs

docs/reference/Readme.md
Removed a few grammatical errors.
=> Updated Readme.md

server/src/services/vls.ts
=> allow vetur.config.cjs

rfcs/001-vetur-config-file.md
=> fix spelling

docs/guide/FAQ.md, server/src/services/vls.ts
Hi, thanks very much for Vetur -- it's fantastic!
This PR makes a minor language edit to a warning message. [I have not tested this PR.]
=> Minor language fix in a warning message

README.md, docs/README.md, docs/guide/FAQ.md, docs/guide/Readme.md, docs/guide/intellisense.md
Thanks for the wonderful tool,
Was reading the docs and found some links that were outdated
=> fix broken links in docs

CHANGELOG.md, server/src/modes/style/stylus/index.ts, server/src/modes/style/stylus/stylus-supremacy.d.ts
=> look for a .stylintrc file when formatting stylus code

docs/guide/vti.md
=> fix: interpolation url reference in vti

docs/guide/formatting.md
=> Fixed typo

README.md
=> chore: stepsize sponsorship

README.md
=> chore: bloop sponsorship

README.md
=> chore: tabnine sponsorship

docs/guide/setup.md
Improves readability in the setup guide by fixing some grammatical errors.
=> Update grammatical errors in setup guide

server/src/modes/script/javascript.ts, server/src/modes/template/index.ts, server/src/modes/test/region.test.ts, server/src/services/vueInfoService.ts
=> fix: several typos

languages/vue-html-language-configuration.json
Fixes https://github.com/vuejs/vetur/issues/3141
=> Bracket pair colorization support for VSCode 1.60+

server/README.md
=> fixed: modify vls readme
